Repository hedia-team/.github, pull requests merged in 2024-07, with the labels that each got.

#66 fix(create-pull-request): wrap variables with quotes
  .github/actions/create-pull-request/action.yml
Labels: fix, patch

#67 fix(update-please): use unique branch
  .github/workflows/update-please.yml
Labels: fix, patch

#68 fix(update-please): Always make a new PR
  .github/actions/create-pull-request/action.yml
Labels: fix, patch

#69 fix(update-please): remove backend as a target topic option for Update Please
  .github/workflows/update-please.yml
Labels: fix, patch

#70 feat(workflows): add a package-lint workflow
  .github/workflows/ci-package-lint.yml
  .prettierrc.json
Labels: feature, minor

#71 feat: label update-please PRs as type deps
  .github/actions/set-labels/action.yml
  .github/workflows/approve-please.yml
  .github/workflows/update-please.yml
Labels: feature, minor

#72 fix(approve-please): add default label 'deps'
  .github/workflows/approve-please.yml
Labels: fix, patch

#74 fix: redocly bundle should fail if missing
  .github/workflows/ci-redocly.yml
Labels: fix, patch

#76 feat: add bulk actions
  .github/workflows/bulk-approve-please.yml
  .github/workflows/bulk-deploy-please.yml
  .github/workflows/bulk-issues-please.yml
  .github/workflows/bulk-release-please.yml
  .github/workflows/bulk-update-please.yml
  .github/workflows/deploy-please.yml
  .github/workflows/release-please.yml
  .github/workflows/update-please.yml
Labels: feature, minor

#77 fix(release-please): update output name as we are using v3
  .github/workflows/release-please.yml
Labels: fix, patch

#78 fix(release-please): fix potential typo and adopt new strategy
  .github/workflows/release-please.yml
Labels: fix, patch

#79 fix: update some of the links to reference bulk actions
  .github/workflows/bulk-approve-please.yml
  .github/workflows/bulk-issues-please.yml
Labels: fix, patch

#80 fix!: delete bulk deploy please flow (it never worked anyway)
  .github/workflows/bulk-deploy-please.yml
Labels: fix, major

#82 feat: add package filter to [bulk-]update-please
  .github/workflows/bulk-update-please.yml
  .github/workflows/update-please.yml
Labels: feature, minor
