Repository hedia-team/.github, pull requests merged in 2024-06, with the labels that each got.

#39 feat!: update workflow
  .github/actions/create-pull-request/action.yml
  .github/actions/set-labels/action.yml
  .github/workflows/assign-to-project.yml
  .github/workflows/ci-eslint.yml
  .github/workflows/ci-prettier.yml
  .github/workflows/ci-redocly.yml
  .github/workflows/ci-sonarcloud.yml
  .github/workflows/ci-test.yml
  .github/workflows/ci-typescript.yml
  .github/workflows/dockerize-please.yml
  .github/workflows/issue.yml
  .github/workflows/lint-pr.yml
  .github/workflows/publish-please.yml
  .github/workflows/pull-request.yml
  .github/workflows/release-please.yml
  .github/workflows/update-please.yml
Labels: feature, major

#40 feat: deploy-please
  .github/workflows/deploy-please.yml
  .github/workflows/dockerize-please.yml
  .github/workflows/issue.yml
  .github/workflows/publish-please.yml
  .github/workflows/pull-request.yml
  .github/workflows/release-please.yml
  .github/workflows/update-please.yml
Labels: feature, minor

#41 fix: tag release PR with the right label
  .github/actions/set-labels/action.yml
Labels: fix, patch

#42 feat(workflows): add `approve-please`
  .github/workflows/approve-please.yml
Labels: feature, minor

#43 fix(approve_please): format output
  .github/workflows/approve-please.yml
Labels: fix, patch

#44 fix(workflows): make the conventional commit check allow any non-whitespace character for the scope
  .github/actions/set-labels/action.yml
Labels: fix, patch

#45 fix(approve-please): wrap body with quotes
  .github/workflows/approve-please.yml
Labels: fix, patch

#48 fix(approve-please): delay the checks check and use `gh pr view` to do it
  .github/workflows/approve-please.yml
Labels: fix, patch

#49 fix(approve-please): use gh pr checks and allow SKIPPED
  .github/workflows/approve-please.yml
Labels: fix, patch

#50 feat: run update please
  .github/workflows/update-please.yml
Labels: feature, minor

#52 fix: add assignee only if PR is created
  .github/actions/create-pull-request/action.yml
  .github/workflows/update-please.yml
Labels: fix, patch

#51 fix(update-please): better description
  .github/workflows/update-please.yml
Labels: fix, patch

#56 feat: support RabbitMQ in the test workflow
  .github/workflows/ci-test.yml
Labels: feature, minor

#58 feat(update-please): run npm audit fix
  .github/workflows/update-please.yml
Labels: feature, minor

#59 fix(update-please): set minor as the default target
  .github/workflows/update-please.yml
Labels: fix, patch

#60 fix(update-please): check all PRs status
  .github/actions/create-pull-request/action.yml
Labels: fix, patch

#61 feat: add issue-please workflow
  .github/workflows/issue-please.yml
Labels: feature, minor
