Repository hedia-team/.github, pull requests merged in 2024-09, with the labels that each got.

#84 feat: use lcov for Sonarcloud instead of coverage.xml
  .github/workflows/ci-sonarcloud.yml
  .github/workflows/ci-test.yml
Labels: feature, minor

#85 chore: add colour to the logo on the hedia-team landing page
  assets/hedia-logo.svg
Labels: chore

#86 feat: load env from 1password
  .github/workflows/ci-test.yml
Labels: feature, minor

#87 fix: ignore when env file is not in 1password
  .github/workflows/ci-test.yml
Labels: fix, patch

#88 feat: take the test report from the PR and attach it to the release
  .github/workflows/bulk-update-please.yml
  .github/workflows/ci-sonarcloud.yml
  .github/workflows/ci-test.yml
  .github/workflows/release-please.yml
Labels: feature, minor

#89 fix(test): do not overwrite env
  .github/workflows/ci-test.yml
Labels: fix, patch

#91 fix: Prefer sentence case in pull requests
  .github/workflows/update-please.yml
Labels: fix, patch

#92 feat: Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: feature, minor

#93 fix: Improve the feature request template a little bit
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: fix, patch

#94 fix: Remove config.yml to allow blank issues
  .github/ISSUE_TEMPLATE/config.yml
Labels: fix, patch
