Repository hedia-team/.github, pull requests merged in 2024-04, with the labels that each got.

#21 feat(workflows)!: deprecate release-and-publish workflow
  .github/workflows/release-and-publish.yml
Labels: chore, ci, feature

#22 fix(workflows): enable SLACK_APP_TOKEN secret to be passed along
  .github/workflows/continuous-integration.yml
Labels: ci, fix

#25 feat: env file
  .github/workflows/eslint.yml
  .github/workflows/prettier.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/test.yml
  .github/workflows/typescript.yml
  .prettierrc.json
Labels: feature, minor

#26 feat(workflows)!: remove deprecated continuous integration workflow
  .github/workflows/continuous-integration.yml
Labels: feature, major
