Repository hedia-team/.github, pull requests merged in 2024-12, with the labels that each got.

#120 fix: Update the release check to be more permissive
  .github/actions/set-labels/action.yml
Labels: fix, patch

#122 feat(release-please): List all changes made to a repo in the changelog
  .github/workflows/release-please.yml
Labels: feature, minor

#123 feat: Replace custom `deps` type by `chore`
  .github/actions/set-labels/action.yml
  .github/workflows/bulk-approve-please.yml
  .github/workflows/release-please.yml
  .github/workflows/update-please.yml
Labels: feature, minor

#124 fix(issue): Stop setting labels as it's not the right format
  .github/workflows/issue.yml
Labels: fix, patch

#126 feat: Add additional details to Update Please
  .github/workflows/update-please.yml
Labels: feature, minor

#128 feat: Enable passing a specific version number to release-please
  .github/workflows/release-please.yml
Labels: feature, minor

#130 chore: Update to latest standards
  .github/workflows/self-release-please.yml
  package-lock.json
  package.json
Labels: chore, patch
